### ISSUE TITLE
Cannot select options on intro screen

### ISSUE THREAD

**Issue by risoy** [mandarinx/Deflector#1]
I can only use the arrow up and down keys to swap between the options on the intro screen. I hear nice music and a bop when I hit the arrow keys. However, I cannot select the options. Not with the Enter key, Space bar nor any other plausible key.

I use a Mac on macOS 10.13.6 High Sierra.

**Comment by mandarinx** [comment]
Thanks for reporting this issue. I will look into it.
Did you also try pressing the x-key?

**Comment by risoy** [comment]
Thank you @mandarinx. That was it. Wasn't aware that it was the x-key that was the selector.
